---
name: feishu
version: 1

handle:
- expire: if(path ~ "(.*)\.(js|css|jpg|png|gif|ico)") time 31536000
- compress: if(out_header["Content-Length"] >= 1240) compress
- compress: if(out_header["Content-Type"] ~ "text") compress 
- compress: if(path ~ "/css/") compress
- compress: if(path ~ "/js/") compress
...
